FROM node:18-alpine

# or WORKDIR /usr/src/app
WORKDIR /app

# Copy everything to container besides the files from .dockerignore
COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

EXPOSE 3000

# npm run start:dev
CMD [ "npm", "run", "start:prod" ]